<?php

namespace Src\UI\Models;



use Src\Application\Base\Response;
use Src\Application\Implement\UserEntityService;
use Src\Domain\Abstracts\IEntity;
use Src\Domain\Abstracts\IRepository;
use Src\Domain\Abstracts\IUnitOfWork;

class UserModel extends UserEntityService
{
    public function __construct(IUnitOfWork $iUnitOfWork, IRepository $repository)
    {
        parent::__construct(
            $iUnitOfWork,
            $repository
        );
    }

    /**
     * @param int $id
     * @return array|\JsonSerializable|object|IEntity|Response
     */
    public function find(int $id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $entity
     * @return array|object|Response
     */
    public function findBy(array $entity = [])
    {
        return parent::findBy($entity); // TODO: Change the autogenerated stub
    }

    /**
     * @param IEntity $entity
     * @return array|bool|\JsonSerializable|object|Response
     */
    public function create(IEntity $entity)
    {
        return parent::create($entity); // TODO: Change the autogenerated stub
    }

    /**
     * @param IEntity $entity
     * @return bool|object|Response
     */
    public function delete(IEntity $entity)
    {
        return parent::delete($entity); // TODO: Change the autogenerated stub
    }

    /**
     * @return array|\JsonSerializable|object|Response
     */
    public function getAll()
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }

    /**
     * @param IEntity $entity
     * @return array|bool|\JsonSerializable|object|Response
     */
    public function update(IEntity $entity)
    {
        return parent::update($entity); // TODO: Change the autogenerated stub
    }
}
