<?php

namespace Src\Test\Domain\Entity;

use Src\Domain\Base\BuilderFactory;
use Src\Domain\Entity\UserEntity\UserEntity;
use Src\Test\Test;


class UserEntityTest extends Test
{

    /**
     * @var UserEntity
    */
    private $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new UserEntity(1,"zeros","toor","wowzeros2@gmail.com");
    }
    /**
     * @test Get in UserEntity
    */
    public function testGetId()
    {
        $this->assertEquals("1",$this->user->getId());
        $this->prontoPrint("testGetId success","success");
    }

    public function testGetUsername()
    {
        $this->assertEquals("zeros",$this->user->getUsername());
        $this->prontoPrint("testGetUsername success","success");
    }

    public function testGetEmail()
    {
        $this->assertEquals("wowzeros2@gmail.com",$this->user->getEmail());
        $this->prontoPrint("testGetEmail success","success");
    }

    public function testGetPassword()
    {
        $this->assertEquals(sha1("toor"),$this->user->getPassword());
        $this->prontoPrint("testGetPassword success","success");
    }

    /**
     * @test BuilderFactory UserEntity
     */
    public function createUser(){
        $this->assertEquals(BuilderFactory::createUser(1,"zeros","toor","wowzeros2@gmail.com"),$this->user);
        $this->prontoPrint("createUser success","success");
    }
}
